'use strict';
const waitingSources={
 asylum:{title:'People in the UK asylum system, June 2026',publisher:'Home Office',date:'2026-08-27',url:'https://www.gov.uk/government/statistics/immigration-system-statistics-year-ending-june-2026/how-many-people-are-in-the-uk-asylum-system',locator:'Sections 1–2; Asy_D03 and ASY_03'},
 tribunal:{title:'Tribunal statistics, April–June 2026',publisher:'Ministry of Justice',date:'2026-09-10',url:'https://www.gov.uk/government/statistics/tribunals-statistics-quarterly-april-to-june-2026/tribunal-statistics-quarterly-april-to-june-2026',locator:'Section 5, Immigration and Asylum; FIA_4 and timeliness'},
 crossings:{title:'Detected entry routes: measurement limits',publisher:'Home Office',date:'2026-08-27',url:'https://www.gov.uk/government/statistics/immigration-system-statistics-year-ending-june-2026/how-many-people-come-to-the-uk-via-illegal-entry-routes',locator:'Sections 1 and 3'}
};
const waitingMeasures=[
 {id:'initial-people',title:'Awaiting an initial decision',value:40168,display:'40,168',unit:'people',period:'30 June 2026',population:'Main applicants and dependants awaiting an initial asylum decision',kind:'Snapshot',note:'Down 56% from June 2025 (publisher-rounded).',source:'asylum',exclusions:'Excludes later appeal and removal stages. Not the number of new claims this quarter.'},
 {id:'initial-cases',title:'The same initial queue, counted as cases',value:32401,display:'32,401',unit:'cases',period:'30 June 2026',population:'Main applicants awaiting an initial asylum decision',kind:'Snapshot',note:'The same queue as 40,168 people, counted differently.',source:'asylum',exclusions:'Dependants are not separate cases. Do not add this count to the people count.'},
 {id:'appeals-open',title:'Open immigration and asylum appeals',value:156000,display:'156,000',unit:'cases · rounded',period:'30 June 2026',population:'All First-tier Tribunal Immigration and Asylum Chamber categories',kind:'Snapshot',note:'Up 48% from June 2025 (publisher-rounded). Includes non-asylum appeals.',source:'tribunal',exclusions:'Not an asylum-only total. Excludes Upper Tribunal proceedings. Must not be added to the initial-decision people count.'},
 {id:'appeals-time',title:'Asylum/protection appeal clearance time',value:72,display:'72',unit:'weeks · mean',period:'Appeals cleared April–June 2026',population:'Asylum/Protection appeals cleared by the First-tier Tribunal',kind:'Duration',note:'An average for completed appeals, not a promised wait for a new appeal.',source:'tribunal',exclusions:'Not the age of currently open cases, not a median, and not the entire time from arrival or asylum claim.'}
];
const initialHistory=[['December 2010',7240],['December 2018',35855],['June 2023',175457],['June 2026',40168]];
function waitingLink(id){const s=waitingSources[id];return `<a class="evidence-btn" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.publisher)}: ${esc(s.title)} ↗</a>`;}
function unknownPanel(type){const entries={
 boats:['No official estimate','How many crossings go undetected?','The recorded figures exclude undetected arrivals. The Home Office has not produced an official estimate of all unlawful entries or everyone resident without permission. An unknown number is not zero.','Small boats are relatively visible, but the detection rate is not known here. Falling detections alone cannot establish a fall in all unlawful entries. Visa overstaying is a separate issue.','crossings'],
 backlog:['Publication gap','The full asylum caseload is not current','The reviewed Home Office release has no overall casework breakdown after June 2024 because of a change in caseworking systems.','Initial decisions, appeals and support are different populations. Adding their headlines cannot reconstruct the missing total.','asylum']
 };const [status,title,body,limit,source]=entries[type];return `<section class="panel unknown-panel"><span class="count-tag">${status}</span><h2>${title}</h2><p>${body}</p><p class="subtle">${limit}</p>${waitingLink(source)}<p class="subtle">Reviewed 18 September 2026 · uncertainty is shown explicitly</p></section>`;}
function waitingPage(){return heading('WHERE PEOPLE WAIT','Waiting & Backlogs','Separate the first decision, the appeal stage and the time taken to clear a case.')+`<div class="context-strip"><b aria-hidden="true">≠</b><span>A smaller initial queue does not mean every queue has shrunk. These counts use different populations and units.</span></div><div class="cards">${waitingMeasures.map(m=>`<article class="stat-card"><div class="kicker">${m.kind}</div><h3>${esc(m.title)}</h3><div class="stat-number">${m.display}</div><strong>${m.unit}</strong><p class="period">${m.period} · UK</p><p>${m.note}</p><button class="evidence-btn" data-waiting-evidence="${m.id}">Evidence & context ↗</button></article>`).join('')}</div><section class="panel history-panel"><div class="eyebrow">LONGER CONTEXT · SELECTED PUBLISHED SNAPSHOTS</div><h2>People awaiting an initial decision</h2><p>Selected dates, not a continuous annual series. These bars are separate snapshots; the time gaps differ.</p><div class="boat-bars" role="img" aria-label="${initialHistory.map(r=>r.join(': ')).join('; ')}">${initialHistory.map(([label,n])=>`<div class="boat-bar-row"><span>${label}</span><div class="bar-track"><div class="bar-fill" style="width:${n/175457*100}%"></div></div><strong>${n.toLocaleString('en-GB')}</strong></div>`).join('')}</div><p class="subtle">UK · people, including dependants · source vintage 27 August 2026 · reviewed 18 September 2026. Consecutive snapshots must not be added.</p>${waitingLink('asylum')}</section><div class="overview-grid"><section class="panel"><h2>What does “72 weeks” mean?</h2><p>It describes the mean time to clear asylum/protection appeals completed during April–June 2026. Long-running cases closing in a quarter can affect that average.</p><p>It does not predict an individual’s remaining wait. The initial asylum decision occurs at an earlier stage, so this is not a claim-to-final-outcome measure.</p>${waitingLink('tribunal')}</section>${unknownPanel('backlog')}</div><section class="panel"><h2>Three questions, three measures</h2><div class="definitions"><div><h3>How many are waiting?</h3><p>A stock: open cases or people at a specified date.</p></div><div><h3>How old are pending cases?</h3><p>A waiting-age distribution: how long still-open cases have already waited. This breakdown is not imported in this version.</p></div><div><h3>How long did completed cases take?</h3><p>A duration: time from the relevant starting event to clearance, among cases that finished.</p></div></div><p class="scope-note">There is no single end-to-end waiting-time estimate in this module. Do not add averages from different groups of completed cases.</p><div class="downloads"><a class="action" href="#small-boats">Arrival and process ↗</a><a class="action" href="#decisions">Decisions ↗</a><a class="action" href="data/waiting.json" download>Download evidence ↓</a></div></section>`;}
function waitingEvidence(id){const m=waitingMeasures.find(x=>x.id===id);if(!m)return;const s=waitingSources[m.source];$('#evidence-body').innerHTML=`<h2 id="evidence-title">${esc(m.title)}</h2><div class="stat-number">${m.display}</div><dl class="facts">${[['Unit',m.unit],['Period',m.period],['Population',m.population],['Geography','UK'],['Measure',m.kind],['Publisher',s.publisher],['Published',date(s.date)],['Reviewed','18 September 2026'],['Locator',s.locator],['What it does not measure',m.exclusions]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${waitingLink(m.source)}`;$('#evidence').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-waiting-evidence]');if(b)waitingEvidence(b.dataset.waitingEvidence);});
